관통PJT/06_pjt 실습/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/',views.profile_index, name='profile_index'),
    path('<int:user_pk>/profile', views.profile, name="profile"),
    path('<int:user_pk>/follow', views.follow, name="follow"),
]

관통PJT/06_pjt 실습/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    followings = models.ManyToManyField("self", symmetrical=False, related_name='followers')
    

관통PJT/06_pjt 실습/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm,UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCretionForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()

관통PJT/06_pjt 실습/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_GET,require_http_methods,require_POST
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserChangeForm,CustomUserCretionForm
# Create your views here.

@require_http_methods(['GET','POST'])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())
            return redirect('boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request,'accounts/login.html',context)


@require_POST
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('boards:index')


@require_http_methods(['GET','POST'])
def signup(request):
    if request.method == "POST":
        form = CustomUserCretionForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('boards:index')
    else:
        form = CustomUserCretionForm()
    context = {
        'form' : form,
    }
    return render(request,'accounts/signup.html',context)

@require_POST
def follow(request,user_pk):
    you = get_user_model().objects.get(pk=user_pk)
    me = request.user
    if me != you:
        if me in you.followers.all():
            you.followers.remove(me)
        else:
            you.followers.add(me)
    return redirect('accounts:profile', user_pk)



@require_http_methods(['GET','POST'])
def profile(request,user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    articles = person.board_set.all()
    comments = person.comment_set.all()
    followers = person.followers.all()
    followings = person.followings.all()
    context = {
        'person' : person,
        'articles' : articles,
        'comments' : comments,
        'followers' : followers,
        'followings' : followings,
    }
    return render(request,'accounts/profile.html', context)


@require_http_methods(["GET"])
def profile_index(request):
    persons = get_user_model().objects.all()
    context = {
        'persons': persons
    }
    return render(request, 'accounts/profile_index.html', context)

관통PJT/06_pjt 실습/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>로그인</h1>
<form action="{% url "accounts:login" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='login'>
</form>
{% endblock content %}

관통PJT/06_pjt 실습/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{ person.username }}님의 프로필 페이지</h1>
<div>팔로잉: {{ followings|length }} / 팔로워: {{ followers|length }}</div>

{% if request.user != person %}
    {% if request.user in person.followers.all %}
        <form action="{% url "accounts:follow" person.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value='팔로우 취소'>
        </form>
    {% else %}
    <form action="{% url "accounts:follow" person.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value='팔로우'>
    </form>
    {% endif %}
{% endif %}

<br>
<div>회원번호: {{ person.pk }}</div>
<div>유저이름: {{ person.username }}</div>
<div>가입날짜: {{ person.date_joined }}</div>
<hr>

<h2>유저가 쓴 글</h2>
{% if articles %}
    {% for article in articles %}
        <ul>
            <li><div>글번호: {{ article.pk }}</div></li>
            <li><div>글제목: <a href="{% url "boards:detail" article.pk %}">{{ article.title }}</a></div></li>
        </ul>
        <br>
    {% endfor %}
{% else %}
    <div>아직 작성한 게시글이 없습니다.</div>
{% endif %}
<hr>

<h2>유저가 쓴 댓글</h2>
{% if comments %}
    {% for comment in comments %}
        <ul>
            <li><div>댓글번호: {{ comment.pk }}</div></li>
            <li><div>댓글내용: <a href="{% url "boards:detail" comment.board.pk %}"> {{ comment.content }}</a></div></li>
        </ul>
        <br>
    {% endfor %}
{% else %}
    <div>아직 작성한 댓글이 없습니다.</div>
{% endif %}
<hr>

<h2>팔로워</h2>
{% if followers %}
    {% for follower in followers %}
        <ul>            
            <li><div>팔로워명: <a href="{% url "accounts:profile" follower.pk %}"> {{ follower.username }}</a></div></li>
        </ul>
        <br>
    {% endfor %}
{% else %}
    <div>팔로워 한 사람이 없습니다.</div>
{% endif %}
<hr>

{% endblock content %} 

관통PJT/06_pjt 실습/accounts/templates/accounts/profile_index.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">프로필 페이지</h1>
  </div>
  {% if persons|length == 0 %}
    <div>아직 유저가 없습니다</div>
  {% else %}
  {% for person in persons %}
    <p>유저 : {{ person.username }}</p>  
    <p>상세 프로필 : <a href="{% url 'accounts:profile' person.pk %}" style="text-decoration: none;">[프로필 상세보기]</a></p>
    <hr>
  {% endfor %}
  {% endif %}
</div>
{% endblock content %}

관통PJT/06_pjt 실습/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원가입</h1>
<form action="{% url "accounts:signup" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='signup'>
</form>
{% endblock content %}