관통PJT/06_pjt 실습/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/like_articles', views.like_articles, name='like_articles'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
]

관통PJT/06_pjt 실습/boards/models.py
from django.db import models
from django.conf import settings    

# Create your models here.
class Board(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_articles")
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

관통PJT/06_pjt 실습/boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

관통PJT/06_pjt 실습/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods,require_POST,require_GET
from .models import Board, Comment
from .forms import BoardForm, CommentForm


# Create your views here.
@require_http_methods(["GET"])
def index(request):
    boards = Board.objects.all().order_by('-created_at')
    context = {
        'boards': boards
    }
    return render(request, 'boards/index.html', context)


@require_http_methods(["GET", "POST"])
def detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    like_users = board.like_users.all()

    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')

    comments = board.comments.all()
    comment_form = CommentForm()
    
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
        'like_users' : like_users,
    }
    return render(request, 'boards/detail.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.user == board.author:
        if request.method == 'POST':
                form = BoardForm(request.POST, instance=board)
                if form.is_valid():
                    form.save()
                    return redirect('boards:detail', board.pk)
        else:
            form = BoardForm(instance=board)
        context = {
            'board': board,
            'form': form,
        }
        return render(request, 'boards/update.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            form.save()
            return redirect('boards:index')
    else:
        form = BoardForm()
    context = {
        'form': form,
    }
    return render(request, 'boards/create.html', context)


@login_required
@require_http_methods(["POST"])
def comment(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.author = request.user
            comment.save()
            return redirect('boards:detail', board.pk)


@require_http_methods(["POST"])
def comment_delete(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.author:
        if request.method == 'POST':
            comment.delete()
            return redirect('boards:detail', board_pk)
        

@require_POST
def like_articles(request,pk):
    board = Board.objects.get(pk=pk)
    me = request.user

    if me in board.like_users.all():
        board.like_users.remove(me)
    else:
        board.like_users.add(me)

    return redirect('boards:detail', pk)

관통PJT/06_pjt 실습/boards/templates/boards/create.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">생성 페이지</h1>
  <form action="{% url 'boards:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">생성하기</button>
  </form>
</div>
{% endblock content %}

관통PJT/06_pjt 실습/boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">상세 페이지</h1>
  </div>
  <p>글번호 : {{ board.id }}</p>  
  <p>글제목 : {{ board.title }}</p>
  <p>글내용 : {{ board.content }}</p>
  <p>작성날짜 : {{ board.created_at }}</p>
  <p>수정날짜 : {{ board.updated_at }}</p>
  <hr>
 
      <div class="mb-5 d-flex justify-content-between">
        <div class = 'flex-container'>
            <div class="badge bg-success badge-aligned">좋아요 : {{ like_users|length }} </div>
        <form action="{% url "boards:like_articles" board.pk %}" method="POST">
          {% csrf_token %}
          {% if request.user in board.like_users.all %}
            <input class="btn btn-success ms-2" type="submit" value="좋아요 취소">
          {% else %}
            <input class="btn btn-success ms-2" type="submit" value="좋아요">
          </form>
          {% endif %}
        </form>
        <a href="{% url 'boards:index' %}"><button class="btn btn-primary ms-2">메인 페이지로</button></a>
        </div>
        {% if request.user.is_authenticated %}
          {% if request.user == board.author %}
            <div class="d-flex">
              <a href="{% url 'boards:update' board.id %}"><button class="me-3 btn btn-success">수정하기</button></a>
              <form action="{% url 'boards:detail' board.id%}" method='POST'>
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">삭제하기</button>
              </form> 
            </div>
        {% endif %}
      </div>
    <form action="{% url 'boards:comment' board.id %}" method='POST'>
      {% csrf_token %}
      <button class="btn btn-secondary" style="float: right;" type="submit">작성하기</button>
      {{ comment_form.as_p }}
    </form>
  {% else %}
    <div class="d-flex">댓글을 작성하시려면 로그인을 해주세요.</div>
  {% endif %}

  <div class="mt-5">
      {% if comments|length == 0 %} 댓글이 없습니다.
      {% else %}
        {% for comment in comments %}
          <div class="my-3 d-flex justify-content-between">
            <div>
              <span>{{ comment.author.username }} : {{ comment.content }}</span>
              <span class="mx-2">({{ comment.created_at }})</span>
            </div>

            {% if request.user == comment.author %}
              <div>
                <form action="{% url 'boards:comment_delete' board.id comment.id %}" method='POST'>
                  {% csrf_token %}
                  <button class="btn btn-light">삭제하기</button>
                </form>
              </div>
            {% endif %}

          </div>
          <hr>
        {% endfor %}
      {% endif %}
  </div>
</div>
{% endblock content %}

관통PJT/06_pjt 실습/boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">메인 페이지</h1>
    <a style="height: 70%;" href="{% url 'boards:create' %}"><button class="btn btn-info">생성하기</button></a>
  </div>
  {% if boards|length == 0 %}
    <div>아직 게시글이 없습니다</div>
  {% else %}
    {% for board in boards %}
      <p>글번호 : {{ board.id }}</p>  
      <p>글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
      <p>작성자 : {{ board.author.username }} </p>
      <hr>
    {% endfor %}
  {% endif %}
</div>
{% endblock content %}

관통PJT/06_pjt 실습/boards/templates/boards/update.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">수정 페이지</h1>
  <form action="{% url 'boards:update' board.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
</div>
{% endblock content %}